001. Web/MITT_Irsyad_Warid/MITT.01.Web/Models/ErrorViewModel.cs
using System;

namespace MITT._01.Web.Models
{
    public class ErrorViewModel
    {
        public string RequestId { get; set; }

        public bool ShowRequestId => !string.IsNullOrEmpty(RequestId);
    }
}

001. Web/MITT_Irsyad_Warid/MITT.01.Web/Controllers/HomeController.cs
using Microsoft.AspNetCore.Mvc;
using Microsoft.Extensions.Logging;
using MITT._01.Web.Models;
using System;
using System.Collections.Generic;
using System.Diagnostics;
using System.Linq;
using System.Threading.Tasks;

namespace MITT._01.Web.Controllers
{
    public class HomeController : Controller
    {
        private readonly ILogger<HomeController> _logger;

        public HomeController(ILogger<HomeController> logger)
        {
            _logger = logger;
        }

        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Privacy()
        {
            return View();
        }

        [ResponseCache(Duration = 0, Location = ResponseCacheLocation.None, NoStore = true)]
        public IActionResult Error()
        {
            return View(new ErrorViewModel { RequestId = Activity.Current?.Id ?? HttpContext.TraceIdentifier });
        }
    }
}

001. Web/MITT_Irsyad_Warid/MITT.01.Web/Controllers/SkillController.cs
using Microsoft.AspNetCore.Mvc;
using MITT.Commons.ViewModels;
using MITT.Repository.Interfaces;
using System.Collections.Generic;
using System.Threading.Tasks;

namespace MITT._01.Web.Controllers
{
    public class SkillController : Controller
    {
        private readonly ISkillModelAccess _skillModelAccess;

        public SkillController(ISkillModelAccess skillModelAccess)
        {
            _skillModelAccess = skillModelAccess;
        }
        public async Task<IActionResult> Index(string search)
        {
            var data = await _skillModelAccess.GetAll();
            List<SkillViewModel> data1 = new List<SkillViewModel>();

            if (data.IsSuccess)
            {
                if (search != null)
                {
                    foreach (var item in data.Data)
                    {
                        if (item.SkillName.ToLower().Contains(search.ToLower()))
                        {
                            SkillViewModel b = new SkillViewModel
                            {
                                SkillId = item.SkillId,
                                SkillName = item.SkillName,
                            };
                            data1.Add(b);
                        }
                    }
                }
                else
                {
                    foreach (var i in data.Data)
                    {
                        data1.Add(i);
                    }
                }
                return View(data1);
            }
            return View(data);
        }
        public IActionResult CreateMITT()
        {
            return View();
        }

        [HttpPost]
        public async Task<IActionResult> CreateMITT(SkillViewModel a)
        {
            await _skillModelAccess.PostCreate(a);

            return RedirectToAction("Index");
        }
        public async Task<IActionResult> EditMITT(int id)
        {
            var data = await _skillModelAccess.GetById(id);

            SkillViewModel a = new SkillViewModel();
            if (data.IsSuccess && data.Data != null)
            {
                a.SkillId = id;
                a.SkillName = data.Data.SkillName;
            };
            return View(a);
        }

        [HttpPost]
        public async Task<IActionResult> EditMITT(SkillViewModel a, int id)
        {
            await _skillModelAccess.PostUpdated(a);
            return RedirectToAction("Index");
        }

        public async Task<IActionResult> DeleteMITT(int id)
        {
            var data = await _skillModelAccess.GetById(id);

            SkillViewModel a = new SkillViewModel();
            if (data.IsSuccess && data.Data != null)
            {
                a.SkillId = id;
                a.SkillName = data.Data.SkillName;
            };
            return View(a);
        }

        [HttpPost]
        public async Task<IActionResult> DeleteMITT(SkillViewModel a, int id)
        {
            var data2 = await _skillModelAccess.GetById(id);

            a.SkillName = data2.Data.SkillName;

            await _skillModelAccess.PostDelete(a);
            return RedirectToAction("Index");
        }
    }
}

001. Web/MITT_Irsyad_Warid/MITT.01.Web/Controllers/SkillLevelController.cs
using Microsoft.AspNetCore.Mvc;

namespace MITT._01.Web.Controllers
{
    public class SkillLevelController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

001. Web/MITT_Irsyad_Warid/MITT.01.Web/Controllers/UserController.cs
using Microsoft.AspNetCore.Mvc;

namespace MITT._01.Web.Controllers
{
    public class UserController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

001. Web/MITT_Irsyad_Warid/MITT.01.Web/Controllers/UserProfileController.cs
using Microsoft.AspNetCore.Mvc;

namespace MITT._01.Web.Controllers
{
    public class UserProfileController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

001. Web/MITT_Irsyad_Warid/MITT.01.Web/Controllers/UserSkillController.cs
using Microsoft.AspNetCore.Mvc;

namespace MITT._01.Web.Controllers
{
    public class UserSkillController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

001. Web/MITT_Irsyad_Warid/MITT.01.Web/Views/Home/Index.cshtml
@{
    ViewData["Title"] = "Home Page";
}

<div class="text-center">
    <h1 class="display-4">Welcome</h1>
    <p>Learn about <a href="https://docs.microsoft.com/aspnet/core">building Web apps with ASP.NET Core</a>.</p>
</div>

001. Web/MITT_Irsyad_Warid/MITT.01.Web/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - MITT._01.Web</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">MITT._01.Web</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Index">Home</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2022 - MITT._01.Web - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

001. Web/MITT_Irsyad_Warid/MITT.01.Web/Views/Skill/CreateMITT.cshtml
@model MITT.Commons.ViewModels.SkillViewModel


@{ ViewData["Title"] = "Add Skill"; }

<h1>Add</h1>

<h4>Skill</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="CreateMITT">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="SkillId" class="control-label"></label>
                <input asp-for="SkillId" class="form-control" />
                <span asp-validation-for="SkillId" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="SkillName" class="control-label"></label>
                <input asp-for="SkillName" class="form-control" />
                <span asp-validation-for="SkillName" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary btn-sm" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

001. Web/MITT_Irsyad_Warid/MITT.01.Web/Views/Skill/DeleteMITT.cshtml
@model MITT.Commons.ViewModels.SkillViewModel

@{
    ViewData["Title"] = "Delete Skill";
}


<hi>Delete Skill</hi>

<div>
    <dl class="row">
        <dt class="col-sm-2">@Html.DisplayNameFor(o=>o.SkillName)</dt>
        <dt class="col-sm-10">@Html.DisplayFor(o=>o.SkillName)</dt>

        <form asp-action="DeleteMITT">
            <input asp-route-id="@Model.SkillId" type="submit" value="Delete" class="btn btn-danger btn-sm" />
        </form>
    </dl>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts{
    @{ await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

001. Web/MITT_Irsyad_Warid/MITT.01.Web/Views/Skill/EditMITT.cshtml
@model MITT.Commons.ViewModels.SkillViewModel

@{
    ViewData["Title"] = "Edit Skill";
}

<h1>Edit</h1>
<h4>Skill</h4>

<div class="row">
    <div class="col-md_4">
        <form asp-action="EditMITT">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="SkillName" class="control-label"></label>
                <input asp-for="SkillName" class="form-control" />
                <span asp-validation-for="SkillName" class="text-danger"></span>
            </div>

            <div class="form-group">
                <input type="submit" value="Edit" class="btn btn-primary btn-sm" />
            </div>
        </form>
    </div>
</div>

001. Web/MITT_Irsyad_Warid/MITT.01.Web/Views/Skill/Index.cshtml
@model IEnumerable<MITT.Commons.ViewModels.SkillViewModel>

@{
    ViewData["Title"] = "Skills";
    //Layout = "~/Views/Shared/_AceAdminLayout.cshtml";

}

<h1>Skills</h1>
<br />
<div class="hidden-sm hidden-xs action-buttons">
    <table class="table table-bordered">
        <tr>
            <form asp-action="Index">
                <td align="left">
                    @using (Html.BeginForm("Index", "Skill", FormMethod.Get))
                    {
                        @Html.TextBox("search")
                        <input type="submit" value="Search" align="right" />
                    }
                </td>
            </form>
            <td align="right">
                <a class="btn btn-primary btn-sm" asp-action="CreateMITT" >
                    Create
                </a>
            </td>
        </tr>
    </table>
</div>

<br />
<div class="table-responsive">
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>@Html.DisplayNameFor(model => model.SkillId)</th>
                <th>@Html.DisplayNameFor(model => model.SkillName)</th>
                <th>Action</th>
            </tr>
        </thead>
        <tbody>
            @{ foreach (var item in Model)
                {
                    <tr>
                        <td>@Html.DisplayFor(modelItem => item.SkillId)</td>
                        <td>@Html.DisplayFor(modelItem => item.SkillName)</td>
                        <td>
                            <div class="hidden-sm hidden-xs btn-group">
                                <a class="btn btn-success btn-sm" asp-action="EditMITT" asp-route-id="@item.SkillId">
                                    Edit
                                </a>

                                <a class="btn btn-danger btn-sm" asp-action="DeleteMITT" asp-route-id="@item.SkillId">
                                    Delete
                                </a>
                            </div>
                        </td>
                    </tr>
                } }
        </tbody>
    </table>
</div>